apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hikvision-doorbell.fullname" . }}-secrets
  labels:
    {{- include "hikvision-doorbell.labels" . | nindent 4 }}
type: Opaque
stringData:
  doorbell_username: {{ .Values.doorbell.username | quote }}
  doorbell_password: {{ .Values.doorbell.password | quote }}
  mqtt_username: {{ .Values.mqtt.username | quote }}
  mqtt_password: {{ .Values.mqtt.password | quote }}
