{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hikvision-doorbell.serviceAccountName" . }}
  annotations:
    "rbac.authorization.kubernetes.io/autoupdate": "true"
  labels:
    {{- include "hikvision-doorbell.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
